apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gauravapp       
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mayur21486/argocd_deploy.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: gauravapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

