apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gauravapp-prod    
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mayur21486/argocd_deploy.git
    targetRevision: master
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: gauravapp-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

