apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: mayur21486/helloapp:da8f71ee7f092491a3760d0007f6c85debaa7ac4
        ports:
        - containerPort: 80
